Abdulbawab
HackYourFuture/JavaScript1 pull request #106
Opened 2019-04-30 09:54 UTC by Albawab

2019-05-01 20:11 UTC, marcianoviereck requested changes
The homework looks good! and nice!

I think you forgot a small part of the homework though

2019-05-01 20:11 UTC, marcianoviereck commented on js1-2-1.js
> +let Arabic = "مرحبا ايها العالم",
Fancy! This is also a nice way to do this!

2019-05-01 20:11 UTC, marcianoviereck commented on js1-2-10.js
> +let  multipleTypes = [2, "Sam", true];
This can be `const` since the value won't change anymore

2019-05-01 20:11 UTC, marcianoviereck commented on js1-2-3.js
> +  console.log("the value of x will be: number");
I don't think the value will be `number`:)

2019-05-01 20:11 UTC, marcianoviereck commented on js1-2-5.js
> + console.log(Math.max(z,a));
Ah nice! Good solution!

2019-05-01 20:11 UTC, marcianoviereck commented on js1-2-6.js
> +let more_Sports = new Array();
You can remove this one, since you don't use it

2019-05-01 20:11 UTC, marcianoviereck commented on js1-2-8.js
> +console.log("The value of my variable foo is: " + firstNumber);
foo = firstNumber

it's fine, just that you wrote `foo` instead of `firstNumber`:)

2019-05-01 20:11 UTC, marcianoviereck commented on js1-2-8.js
> +    secondNumber = 10;
I think you can remove`secondNumber` because it is not used

2019-05-01 20:11 UTC, marcianoviereck commented on js1-2-8.js
> +if(typeof(firstNumber) == typeof(firstString)){
I think you forgot to add more variable (with different types):

```
8.1 First declare at least four variables and assign them different data types.
```

2019-05-02 11:55 UTC, marcianoviereck requested changes
One last thing, I think you forgot two data-types in the `js-1-2-8.js` file

2019-05-02 11:55 UTC, marcianoviereck commented on js1-2-8.js
> +
Ah, I think it's almost correct, I think you need to add two variables:

one for the `array` data-type and one of the `boolean` data type. Then compare those as well. Then the homework is approved!

2019-05-19 19:15 UTC, wouterkleijn commented
Thanks @marcianoviereck for providing feedback. @Albawab Can you please address Marciano's comments? Thanks!

2019-05-21 11:06 UTC, marcianoviereck requested changes
I found one last thing that is not correct yet.

2019-05-21 11:06 UTC, marcianoviereck commented on js1-2-8.js
> +let firstString = ture,
this is not valid a boolean value (and will not compile). If you can fix this then it is fine

2019-06-02 07:49 UTC, closed without merging