irfan-homework
HackYourFuture/JavaScript1 pull request #112
Opened 2019-05-07 13:54 UTC by irfankaradeniz

javascripthomework-irfan

2019-05-09 12:27 UTC, marcianoviereck requested changes
The homework is fine, but can you only split it up in separate files? Then it will be approved.

2019-05-09 12:27 UTC, marcianoviereck commented on Week2/irfan-homework.js
> +// Question 1
Can you split up the homework in different parts:

> For all the following exercises create a new .js file. Try to find a proper name for each file or make a small comment about what it does inside for future reference.

2019-05-09 12:27 UTC, marcianoviereck commented on Week2/irfan-homework.js
> +let h = Math.max(a,z);
nice solution!

2019-05-09 12:27 UTC, marcianoviereck commented on Week2/irfan-homework.js
> +function checkType(variable1,variable2) {
Really nice solution!

2019-05-10 21:24 UTC, marcianoviereck approved these changes
Nice, approved!

2019-05-19 19:18 UTC, wouterkleijn commented
Thanks @irfankaradeniz for making the necessary changes.

2019-06-02 07:50 UTC, closed without merging