finished project for homework week1
HackYourFuture/JavaScript1 pull request #170
Opened 2019-09-20 17:21 UTC by ceylanbaysalaydin

Homework week 1 Ceylan Baysal

2019-09-24 06:33 UTC, yash-kapila requested changes
Hi @ceylanbaysalaydin - I've reviewed your homework and am satisfied with it. However, there is one question regarding comparison of typeof variables where I have added a suggestion. Could you please have a look into it and let me know when you have corrected it? I think it would help you improve. Please drop me a message on Slack once you have incorporated asked changes. Good luck!

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/compareArrays.js
> +array.length==array2.length ? console.log("They are the same!") : console.log("Two different sizes")
Double thumbs up for using `use strict` and using `const` keyword. 👍 👍

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/errorDebugging.js
> +console.log('I\'m awesome');
👍

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/lengthOfStr.js
> +let mySentence = "Programming is so interesting!"
`const` instead of `let` here please since we aren't reassigning this variable

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/logArray.js
> +favAnimals.push("Piglet");
`const` instead of `let` here please

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/logHello.js
> +    console.log(helloArray[i]);
👏 for logic but a minor indentation(spacing) issue when creating the array. You could also use an object here like:
```
const languages = {
  nederlands: 'Hallo, Wereld',
  spanish: 'Hola, mundo',
  // and so on
};
```

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/logNum.js
> +console.log(numberX);
👍

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/logRemainder.js
> +// z%2 gives us the remainder when z divided by 2
👍 for logic but can use `const` here since you aren't reassigning `x`, `y` or `z`

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/logString.js
> +console.log(myString);
👍

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/roundNum.js
> +console.log(highestNum);
`const` instead of `let` here please

2019-09-24 06:33 UTC, yash-kapila commented on Week1/homework/js-exercises/typeChecker.js
> +typeof(str2) != typeof(obj2) ? console.log('Not the same') : console.log("SAME TYPE");
Couple things here:
1. `const` instead of `let` while creating variables
2. `==` operator for comparison in JavaScript is not the safest thing to use. Try and use `===` instead as there are a lot of catches with using double equals which I think you would have covered during last Sunday's lesson.

2019-09-29 07:38 UTC, wouterkleijn commented
Thanks for the extensive feedback @yash-kapila and the changes made @ceylanbaysalaydin

2019-09-29 17:13 UTC, yash-kapila approved these changes

2019-09-29 17:19 UTC, closed without merging