week 1 homework Yalcin TOK
HackYourFuture/JavaScript1 pull request #173
Opened 2019-09-20 18:57 UTC by yalcintok

2019-09-24 07:01 UTC, yash-kapila requested changes
Hi @yalcintok - I've finished reviewing your homework. However, I feel there is some room for improvement and I've added comments as suggestions wherever applicable. Could you please have a look? Please drop me a message on Slack once you have implemented the feedback. Good luck! 🙂

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/arrayOfAnimals.js
> +}
Ah. Couple things here:
1. I am not sure if you are referring to any online material for JavaScript but it might be that it is a bit obsolete. This is because using var instead of let or const as we learnt in Week1 is the old way of doing things. Please try to use `let` or `const` instead of `var` now onwards.
2. 👍 for using `use strict` and the block scope `{}` but there seems to be an indentation problem. Unlike the `if-block` or creating objects using curly braces, you can move it to the following line like:

```
'use strict'

{
  const fruits = [];
  // remaining code goes here
}
```

This makes code more readable. 🙂

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/compareArrays.js
> +    console.log("Two different sizes");
👍 but the same points as before:
1. Using `const` instead of `var`
2. Indentation(spacing) issue 🙂

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/lengthOfString.js
> +    var mySentence = "Programming is so interesting!";
Same points here as before 🙂

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/logError.js
> +    console.log('I\'m awesome');
👍

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/logHello.js
> +    console.log("Hallo Welt"); // in German
👍

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/logNumber.js
> +    console.log(numberX);
Same points as use of `const` and indentation here 🙂

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/logStrings.js
> +    console.log(myString);
Same points as before here

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/remainder.js
> +    console.log(z);// z is equal to 13. And if we execute z modula 3, we get 1 as the conclusion.
Use of `let` instead of `var` and indentation issue here 🙂

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/roundNumber.js
> +    }
Same points as before 🙂

2019-09-24 07:01 UTC, yash-kapila commented on Week1/homework/js-exercises/typeCheker.js
> +    var d = {type:"Fiat", model:"500", color:"white"};
`const` instead of `var` here please

2019-09-29 07:41 UTC, wouterkleijn commented
Thanks @yash-kapila @yalcintok did you have a look at the suggestions made by Yash? Can you please fix some of these issues and let us know when ready? :)

2019-09-29 13:01 UTC, yalcintok commented
Hello Wouter,
Yes I had a look and fixed all the suggestions made by Yash. And all of the solutions I send Yash via Slack. But if necessary I can also share here.

2019-09-29 13:02 UTC, yalcintok commented
In Week1/homework/js-exercises/arrayOfAnimals.js:
'use script';
{
let fruits = [];
console.log("it should be []");
console.log(fruits);
let myFavoriteAnimals = ["Cows", "Dogs", "Horses"];
console.log(myFavoriteAnimals);
myFavoriteAnimals.push("Piglet");
console.log(myFavoriteAnimals);
}
In Week1/homework/js-exercises/compareArrays.js:
'use script';
{
   const a = [12, 24, 36, 48];
   const b = [1 , "odd", 2, "even", 3, 4, 5];
   console.log('The length of the first array is ' + a.length);
   console.log('The length of the second array is ' + b.length);
   if (a.length === b.length) {
   console.log("They are the same!");
   }
   else {
   console.log("Two different sizes");
   }
}
In Week1/homework/js-exercises/lengthOfString.js:
'use script';
{
   const mySentence = "Programming is so interesting!";
   console.log(mySentence.length);
}
In Week1/homework/js-exercises/logError.js:
'use script';
{
   console.log('I\'m awesome');
}
In Week1/homework/js-exercises/logHello.js:
'use script';
{
   console.log("Hallo, Wereld"); //in Dutch
   console.log("Hello, World!"); // in English
   console.log("Selam, dunya"); // in Turkish
   console.log("Silav, cîhan") // in Kurdish
   console.log("Привет, мир"); // in Russian
   console.log("안녕, 세상"); // in Korean
   console.log("હેલો, વિશ્વ"); // in Gujarati
   console.log("Ciao mondo"); // in Italian
   console.log("Γειά σου Κόσμε"); // in Greek
   console.log("Hallo Welt"); // in German
}
In Week1/homework/js-exercises/logNumber.js:
'use script';
{
   const numberX;
   console.log("It should be undefined the value of numberX");
   console.log(numberX);
   numberX = 33;
   console.log("It should be a number the value of numberX");
   console.log(numberX);
}
In Week1/homework/js-exercises/logStrings.js:
'use script';
{
   const myString = "Yalcin Tok";
   console.log("It should be a string the value of myString");
   console.log(myString);
   myString = "Azize TOK";
   console.log("It should be a string the value of myString. It defines my daughter's name");
   console.log(myString);
}
In Week1/homework/js-exercises/remainder.js:
'use script';
{
   let x = 7;
   x = x % 3;
   console.log(x); // x is equal to 7. And if we execute x modula 3, we get 1 as the conclusion.
   let y = 21;
   y = y % 4;
   console.log(y);// y is equal to 21. And if we execute y modula 4, we get 1 as the conclusion.
   let z = 13;
   z = z % 2;
   console.log(z);// z is equal to 13. And if we execute z modula 3, we get 1 as the conclusion.
}
In Week1/homework/js-exercises/roundNumber.js:
'use script';
{
   let z = 7.25;
   console.log(z);
   let a = Math.round(z);
   console.log(a);
   if (z > a){
       console.log("the value of z is the highest value");
   }
}
In Week1/homework/js-exercises/typeCheker.js:
'use script';
{
   const a = "This is a";
   const b = "This is b";
   const c = {firstName:"John", lastName:"Doe", age:50, eyeColor:"blue"};
   const d = {type:"Fiat", model:"500", color:"white"};
   if (typeof(a) === typeof(b)){
   console.log("SAME TYPE");
   }
   if (typeof(a) !== typeof(c)){
   console.log("Not the same ...");
   }
   if (typeof(b) === typeof(a)){
   console.log("SAME TYPE");
   }
   if (typeof(b) !== typeof(d)){
   console.log("Not the same ...");
   }
   if (typeof(c) !== typeof(a)){
   console.log("Not the same ...");
   }
   if (typeof(c) === typeof(d)){
   console.log("SAME TYPE");
   }
   if (typeof(d) !== typeof(a)){
   console.log("Not the same ...");
   }
   if (typeof(d) === typeof(c)){
   console.log("SAME TYPE");
   }
   console.log(typeof(a));
   console.log(typeof(d));
}

2019-09-29 17:16 UTC, yash-kapila commented
Hi @yalcintok - thank you for sharing your update. But could you update your files and do a `git commit` and `git push` with your changes instead of submitting them through a comment message please?

2019-09-29 20:11 UTC, yalcintok commented
hi @yash-kapila 
Yes you are quite right. I am doing that right now.

2019-10-06 07:34 UTC, wouterkleijn commented
Hello @yalcintok thanks for the updated. @yash-kapila what is the status of this PR?

2019-11-24 09:11 UTC, closed without merging