week1 homework ahmet yasin
HackYourFuture/JavaScript1 pull request #193
Opened 2019-11-24 20:26 UTC by ahmtysn

I did this homework last week and i didn't know that i should do commit after every exercise. I'm sorry..Just I have a few commit..

2019-11-25 17:08 UTC, wilgert requested changes
You did really well, only some small things are missing! Please fix these and I will aprove the homework!

2019-11-25 17:08 UTC, wilgert commented on Week1/homework/js-exercises/10_compare.js
> +console.log(`cities variable have ${cities.length} elements..`);
I'm just nitpicking here but correct English would be "cities variable **has**"

2019-11-25 17:08 UTC, wilgert commented on Week1/homework/js-exercises/2_error.js
> +console.log('I\'m awesome');
very good!

2019-11-25 17:08 UTC, wilgert commented on Week1/homework/js-exercises/6_array.js
> +console.log(`${animals[1]} is the second element..`);
the instructions asked to log the second array, not the second item in te array.

2019-11-25 19:05 UTC, ahmtysn commented
i think i fixed according to your advice, thanks for your interest @wilgert

2019-11-26 16:21 UTC, wilgert approved these changes

2019-12-01 14:58 UTC, closed without merging