JS1 week1 HW
HackYourFuture/JavaScript1 pull request #198
Opened 2019-11-27 12:19 UTC by ramziash

2019-11-27 12:20 UTC, ramziash commented
Homework week 1 Ramzi

2019-11-27 16:54 UTC, wilgert requested changes
You did very welll! Please make just some minor improvements as suggested in the comments.

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e1-helloworld.js
> +console.log(hello);
can you make it so it logs all of the strings on separate lines?

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e10-compare arrays.js
> +const myArray1=['HYF', 25, '#bestclassever', {instructor: 'Wilgert'}]
can you come up with a more descriptive name for these variables?

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e2-error debugging.js
> +console.log("I'm awesome");
very good!

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e3-log the number.js
> +console.log('The value of numberX is 20');
nice!

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e5-round a number.js
> +let highest=[]
why do you initialize highest as an empty array here?

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e5-round a number.js
> +    return  console.log(highest=z);
the intention of the instructions was to store the highest value first, and then log it.

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e9-log the remainder.js
> +'use strict'
good job

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e8-type checker.js
> +let object1=['HYF', 25];
this is actually an array

2019-11-27 16:54 UTC, wilgert commented on Week1/homework/js-excercises/e8-type checker.js
> +typeof string1==typeof string2
I expected to see all of these as if statements like the one on line 17

2019-11-30 09:26 UTC, marcianoviereck requested changes
The fixes are looking really good, I only have some small requests and then it's approved!

2019-11-30 09:26 UTC, marcianoviereck commented on Week1/homework/js-excercises/e5-round a number.js
> +console.log(highest)
Ah, nice! You can also use [Math.max](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max)

And don't forget the `;` at the end of the lines,.

2019-11-30 09:26 UTC, marcianoviereck commented on Week1/homework/js-excercises/e5-round a number.js
> +// };
You can remove this code, since it's not used anyways:)

2019-11-30 09:26 UTC, marcianoviereck commented on Week1/homework/js-excercises/e8-type checker.js
> +
Here you can also remove this commented code, since it's not used:)

2019-11-30 09:26 UTC, marcianoviereck commented on Week1/homework/js-excercises/e10-compare arrays.js
> +const Hobbies=['study', 'read', 'hangout', 'eat', 'drink', 'live', 101]
Remember to use `camelCase` here. So I would change `JS_class25` into `jsClass25`. And same for `Hobbies`

2019-11-30 10:52 UTC, marcianoviereck approved these changes
Nice fixes! The homework is approved

2019-12-01 07:44 UTC, wilgert approved these changes

2020-06-23 11:07 UTC, closed without merging