js1HomeWorkW1
HackYourFuture/JavaScript1 pull request #204
Opened 2019-11-29 13:39 UTC by mahmoudbd

2019-11-29 13:41 UTC, mahmoudbd commented
jsHomeWorkW1

2019-11-29 22:00 UTC, eidosam requested changes
Well done, Mahmoud! There are little comments inline, please have a look and try to implement them, if you have any question, don't hesitate to ask!

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise1.js
> +console.log('Hola Mundo!'); // Spaans
💯

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise2.js
> +console.log('I/m awesome');
This solves the problem with the error `SyntaxError` but doesn't show the requested output.

Maybe this document can help to solve this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Escape_notation

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise3.js
> +console.log('The value of X is a number');
After you ran/executed this script; did it meet your expectation? I mean, is `numberX` is really a number at this point?

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise3.js
> +console.log('The new value of the X is 40');
👍

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise5.js
> +}
This shows the highest number between `a` and `z` but doesn't store it in a variable (for example `maxNumber`) as requested.
Hint; https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise6.js
> +let items;
This is not an array!
Have a look at this document maybe can give you a hint https://www.w3schools.com/js/js_arrays.asp

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise6.js
> +myFavoriteAnimals.push('Piglet');
👍

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise7.js
> +console.log(mySentence.length);
👍

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise8.js
> +let FavoriteCities = [ 'Amsterdam', 'Damascus' ];
Nice descriptive variable names! but remember to use camelCase for variables names.

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise8.js
> +}
Try to get used to the strict equality operator `===`, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators#Equality_operators

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise9.js
> +console.log(z);
Can you write in a comment next to each calculation what will be the new value of each variable? 

> For each of these, write in comments what the answer is followed by how you came to that conclusion

2019-11-29 22:00 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise10.js
> +}
👍

2019-11-30 15:31 UTC, mahmoudbd reviewed
Hello Eidosam i have modified exercises 2,3,5,8,9 , could you please check it after ((mahmoudbd wants to merge 2 commits into HackYourFuture:master from mahmoudbd:Mahmoud-JS-week1-HW))? Thanks

2019-11-30 15:31 UTC, mahmoudbd commented on Week1/Homework/js-exercises/Exercise10.js
> +}
Hello Eidosam i have modified exercises 2,3,5,8,9  ,  could you please check it  after ((mahmoudbd wants to merge 2 commits into HackYourFuture:master from mahmoudbd:Mahmoud-JS-week1-HW))? Thanks

2019-11-30 19:07 UTC, eidosam reviewed
Thanks Mahmoud for addressing the comments. There are little enhancements can be done, please see the new remarks.

2019-11-30 19:07 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise3.js
> +console.log('The value of X is undefined');
👍

2019-11-30 19:07 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise6.js
> +let items;
To create an empty array; `const items = [];`

2019-11-30 19:07 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise9.js
> +console.log(z); //expected output: 6.5
The operator you are requested to use is the remainder operator `%` not the division operator `/`
So for example the first case will be:
```
let x = 7;
x = x % 3;
console.log(x); // Expected output is 1, which is the remainder of dividing 7 by 3
```

2019-11-30 19:07 UTC, eidosam commented on Week1/Homework/js-exercises/Exercise5.js
> +console.log(Math.max(z, a)); // expected output: 7.25
The result need to be assigned to a variable, for example `const maxNumber = Math.max(z, a);`

2019-11-30 20:25 UTC, mahmoudbd commented
Thank you very much for the help , could you please check it again?

2019-12-01 07:24 UTC, eidosam approved these changes
Thanks again Mahmoud for addressing the feedback, very well done!

2019-12-01 14:46 UTC, closed without merging