finished project for homework week2
HackYourFuture/JavaScript1 pull request #227
Opened 2019-12-07 15:07 UTC by wesam-k

2019-12-07 15:08 UTC, wesam-k commented
week2-homework-wesam-alkfere

2019-12-09 07:15 UTC, marcianoviereck requested changes
The homework is looking good, I have some small remarks and I think you forgot the "calculator" project: "PROJECT: Grade calculator". Please check the assignment

2019-12-09 07:15 UTC, marcianoviereck commented on Week2/homework/js-exercises/5-Who wants a drink.js
> +  console.log('\"Hey guys, I brought a '+ drinkTray + '!\"');
hah nice!

2019-12-09 07:15 UTC, marcianoviereck commented on Week2/homework/js-exercises/Grade percentage (function).js
> + if(score >= 90 && score <= 100){ //if the score between 90% to 100% the return a value is A
Can you add an extra `tab` here, for the identation. Then it's easier to read:)

2019-12-09 14:06 UTC, closed without merging

2019-12-09 14:07 UTC, wesam-k commented
done