Split REVIEWs and match up with revised schedule
HackYourFuture/JavaScript1 pull request #23
Opened 2017-12-11 13:15 UTC by remarcmij

- Added REVIEW topics for promises.
- Updated VSCode tips.

There still many review topics to be added.

2017-12-11 14:50 UTC, mkruijt requested changes
really nice @remarcmij I really like the different concepts in the fundamentals file. Maybe we can remove the weekly reviews entirely and just link to the specific files in the fundamentals? What do you think?

2017-12-11 14:50 UTC, mkruijt commented on Week7/REVIEW.md
> +• Async VS Sync
we moved async/sync to the next week and promises to this week

2017-12-11 14:50 UTC, mkruijt commented on Week9/REVIEW.md
> +• Promises
see commend above promises is moved to week 7

2017-12-11 15:06 UTC, remarcmij commented
Hi @mkruijt, are you proposing to directly link the topics mentioned in the main README to the specific files in fundamentals? That sounds like a good idea. It removes one level of indirection and more urgently signals where we still have work to do. Is this something you would like to do or shall I make the changes?

2017-12-12 21:02 UTC, mkruijt commented
yes that is what I'm suggesting. I can do it tomorrow 🙂 . If we merge this in the morning!

2017-12-12 21:03 UTC, mkruijt approved these changes

2017-12-12 21:03 UTC, merged