Update README.md
HackYourFuture/JavaScript1 pull request #33
Opened 2018-02-05 22:49 UTC by Kemirdin

I have read this article and I found it very nice for good understanding promises especially for beginners.

2018-02-05 22:51 UTC, Kemirdin commented
hi, I just would like to contribute some article and share with you, I don't know it didn't work.

2018-02-06 11:16 UTC, mkruijt requested changes
Hi @Kemirdin cool that you are contributing, and yes you always have to make a pr! (the master branch is protected)

2018-02-06 11:16 UTC, mkruijt commented on Week1/README.md
> +-You are here: Home / Learn To Program / The 50 Best Websites to Learn JavaScript
hi @Kemirdin thanks for your contribution. Can you delete this line? I don't get why it says "You are here: Home / Learn To Program / " besides that i think it is a good resource to add. I you modify it I will merge your PR

2018-02-06 12:08 UTC, Kemirdin reviewed
it's my pleasure share and contribute.thanks for the merge, I have deleted that line.

2018-02-06 12:08 UTC, Kemirdin commented
it's my pleasure share and contribute.thanks for the merge, I have deleted that line.

2018-02-06 12:11 UTC, mkruijt approved these changes
Thank you!

2018-02-06 12:11 UTC, merged